---
- name: Create Springboot APPs root
  ansible.builtin.file:
    path: /opt/springboot
    state: directory
    mode: "0550"
    owner: root
    group: springboot
    seuser: system_u
    serole: object_r
    setype: usr_t
  become: "{{ sbf_become }}"

- name: Create Springboot LOGs root
  ansible.builtin.file:
    path: /var/log/springboot
    state: directory
    mode: "0550"
    owner: root
    group: springboot
    seuser: system_u
    serole: object_r
    setype: springboot_log_t
  become: "{{ sbf_become }}"

- name: Create Springboot TMP/cache/work root
  ansible.builtin.file:
    path: /srv/springboot
    state: directory
    mode: "0550"
    owner: root
    group: springboot
    seuser: system_u
    serole: object_r
    setype: springboot_var_t
  become: "{{ sbf_become }}"

- name: Create Springboot APPs common bin directory
  ansible.builtin.file:
    path: "/opt/springboot/bin"
    state: directory
    mode: "0555"
    owner: root
    group: springboot
    seuser: system_u
    serole: object_r
    setype: springboot_bin_t
  become: "{{ sbf_become }}"

- name: "Restore SELinux fcontexts for Springboot roots"
  ansible.builtin.shell: >
    bash -c "/sbin/restorecon -RFi /{opt,srv}/springboot /var/{log,lib,tmp}/springboot"
  changed_when: true
  become: "{{ sbf_become }}"
