---

- name: "Create LV for /opt/springboot"
  community.general.lvol:
    vg: "{{ sbf_dedicated_vg_opt }}"
    lv: lv_opt_springboot
    size: "{{ sbf_default_fs_size_g }}g"
    state: present
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_opt

- name: "Initialise the XFS filesystem for /opt/springboot"
  community.general.filesystem:
    fstype: "{{ sbf_fstype }}"
    dev: "/dev/{{ sbf_dedicated_vg_opt }}/lv_opt_springboot"
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_opt

- name: "Mount /opt/springboot LV/FS"
  community.general.mount:
    path: /opt/springboot
    src: "/dev/{{ sbf_dedicated_vg_opt }}/lv_opt_springboot"
    fstype: "{{ sbf_fstype }}"
    state: mounted
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_opt

- name: "Create LV for /srv/springboot"
  community.general.lvol:
    vg: "{{ sbf_dedicated_vg_srv }}"
    lv: lv_srv_springboot
    size: "{{ sbf_default_fs_size_g }}g"
    state: present
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_srv

- name: "Initialise the XFS filesystem for /srv/springboot"
  community.general.filesystem:
    fstype: "{{ sbf_fstype }}"
    dev: "/dev/{{ sbf_dedicated_vg_srv }}/lv_srv_springboot"
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_srv

- name: "Mount /srv/springboot LV/FS"
  community.general.mount:
    path: /srv/springboot
    src: "/dev/{{ sbf_dedicated_vg_srv }}/lv_srv_springboot"
    fstype: "{{ sbf_fstype }}"
    state: mounted
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_srv

- name: "Create LV for /var/log/springboot"
  community.general.lvol:
    vg: "{{ sbf_dedicated_vg_log }}"
    lv: lv_log_springboot
    size: "{{ sbf_default_fs_size_g }}g"
    state: present
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_log

- name: "Initialise the XFS filesystem for /var/log/springboot"
  community.general.filesystem:
    fstype: "{{ sbf_fstype }}"
    dev: "/dev/{{ sbf_dedicated_vg_log }}/lv_log_springboot"
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_log

- name: "Mount /var/log/springboot LV/FS"
  community.general.mount:
    path: /var/log/springboot
    src: "/dev/{{ sbf_dedicated_vg_log }}/lv_log_springboot"
    fstype: "{{ sbf_fstype }}"
    state: mounted
  become: "{{ sbf_become }}"
  when: sbf_dedicated_lv_log
